openapi: 3.0.0
info:
  title: Customer Management API
  version: v1

components:
  schemas:
    username:
      type: string
      minLength: 4
      maxLength: 20
      pattern: '^[a-zA-Z0-9_]+$'
    password:
      type: string
      minLength: 8
      pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^a-zA-Z0-9]).+$'


paths:
   /login:
    post:
      description: Return JWT token (1 hour), set as HttpOnly and SameSite=Lax
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: '#/components/schemas/username'
                password:
                  $ref: '#/components/schemas/password'
      responses:
        '200':
          description: Login success
        '400':
          description: Invalid credentials
        '403':
          description: Already authenticated (optional)